# Generated by Django 2.1.7 on 2019-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrecord',
            name='myText',
        ),
        migrations.AddField(
            model_name='myrecord',
            name='my_text',
            field=models.CharField(default='SOME TEXT', max_length=300),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='my_word_dictionary',
            field=models.CharField(default='SOME MY_WORD_DICTIONARY', max_length=300),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='my_word_list',
            field=models.CharField(default='SOME MY_WORD_LIST', max_length=300),
        ),
    ]
