# Generated by Django 2.1.7 on 2019-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0002_auto_20190401_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecord',
            name='my_text',
            field=models.TextField(default='SOME TEXT'),
        ),
    ]
