# Generated by Django 2.1.7 on 2019-04-02 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0004_auto_20190403_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='word_all_count',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='word_count',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
