# Generated by Django 2.1.7 on 2019-04-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0005_auto_20190403_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='reated_date',
        ),
    ]
