# Generated by Django 2.1.7 on 2019-04-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0007_auto_20190403_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='word_count',
            new_name='word_countt',
        ),
    ]
