# Generated by Django 2.1.7 on 2019-04-02 17:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0013_auto_20190403_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='word',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None),
        ),
        migrations.AlterField(
            model_name='record',
            name='word_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, size=None),
        ),
    ]
