# Generated by Django 2.1.7 on 2019-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0021_auto_20190403_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='word',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='word_count',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
