# Generated by Django 2.1.7 on 2019-04-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0022_auto_20190403_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='word',
        ),
    ]
