# Generated by Django 2.2.1 on 2019-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='None', max_length=100)),
                ('comment', models.TextField(default=0, max_length=20)),
                ('card_num', models.IntegerField()),
                ('score', models.IntegerField()),
                ('bell_flag', models.IntegerField()),
            ],
        ),
    ]
