# Generated by Django 2.2.1 on 2019-05-19 10:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('halligalli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='None', max_length=100)),
                ('card_info', jsonfield.fields.JSONField()),
            ],
        ),
    ]
