# Generated by Django 2.2.1 on 2019-05-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halligalli', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_card',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
